version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
        - MYSQL_DATABASE=cross_platform_db
        - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3309:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local