spring:
  application:
    name: migration
  datasource:
    url: jdbc:mysql://localhost:3309/cross_platform_db
    username: root
    password: 123456
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
